services:
  - type: web
    name: coldbind-script-host
    env: node
    plan: free
    buildCommand: cd ScriptHost && npm install
    startCommand: cd ScriptHost && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
